### ISSUE TITLE
Consider rewording 'Build-time server-side rendering'

### ISSUE THREAD

**Issue by jamelt** [gridsome/gridsome.org#141]
In the 'How It Works' section:

This wording is a bit confusing, describing static site generation as server-side rendering at build-time. Usually, 'server-side' implies the existence of a server. I think that's why this combination of words are kind of confusing when there's no prototypical server in the equation. Are we looking at a developer workstation or a build server as the 'server-side' of things? 

You can see that this wording leads to a bit of confusion and back-and-forth in this thread below:
https://github.com/gridsome/gridsome/issues/193

I think optimizing for clarity is always a good goal when writing. I wouldn't create an issue just to nitpick.

**Comment by robaxelsen** [comment]
@jamelt hello, and thanks for bringing this up! I am sure we can improve the docs.

Instead of rewording, perhaps it would be better to clearly define "server-side", and that covers all of the below?:

- server-side rendering at build time
- server-side rendering via express with gridsome serve
- "laptop-side" rendering at build time

Would you be interested in making a PR for this yourself, @jamelt?

**Comment by robaxelsen** [comment]
@tomtev @hjvedvik feel free to chime in here.

**Comment by jamelt** [comment]
Yes, I'd be glad to make a PR for this, you can assign to me if you'd like.

**Comment by hjvedvik** [comment]
Another thing to consider is that people must understand that each page is rendered in a server context with Node.js and not in a browser context. So `window` and `document` etc isn't available during build-time rendering.

**Comment by robaxelsen** [comment]
> Yes, I'd be glad to make a PR for this, you can assign to me if you'd like.

Awesome! Assigned.
