### ISSUE TITLE
Missing quick-start documentation on fetching data from local sources

### ISSUE THREAD

**Issue by startupengine** [gridsome/gridsome.org#242]
I am looking for the info which appears to be missing from the bottom portion of this doc - 

https://github.com/gridsome/gridsome.org/blob/master/docs/fetching-data.md

Would appreciate if someone could knock out a quick writeup!

**Comment by earthtone** [comment]
I've recently implemented a solution for a couple sites that load data from local Markdown and JSON sources using the `@gridsome/source-filesystem` plugin, so I'd be keen to write up a quick usage example. However, since my solution is dependent on a specific plugin, is it appropriate to document as part of the general `gridsome` documentation or more specifically in the plugin's documentation? I'm happy to contribute to both if others would find it useful.

**Comment by thetre97** [comment]
This docs section now has most of the sections for local data sources filled out.
