### ISSUE TITLE
Small fix related Vuetify documentation

### ISSUE THREAD

**Issue by menteora** [gridsome/gridsome.org#412]
Hi, I followed you guide here: https://gridsome.org/docs/assets-css/#vuetify
Great Work! You saved me!

Vuetify doc's section need only some small fixes.

Here we must add **sass** module to work properly:
```
# With npm
npm install deepmerge sass fibers sass-loader@7.3.1 vuetify-loader --save-dev

# With yarn
yarn add deepmerge sass fibers sass-loader@7.3.1 vuetify-loader --dev

```
And the web page have a small error inside code block here:

```
const VuetifyLoaderPlugin = require('vuetify-loader/lib/plugin');

<-- HTML BREAKS HERE

module.exports = (api) => {
  api.chainWebpack((config, { isServer }) => {
    config.plugin('vuetify-loader').use(VuetifyLoaderPlugin);
  });
```

thank you

**Comment by JVP3122** [comment]
I'm going to also add that if the user is on Windows 10 the following steps need to be taken before even doing this (can't install fibers on Windows right out of the box)
In order to install fibers you first need to properly install [node-gyp](https://github.com/nodejs/node-gyp#on-windows):
`npm install --global --production windows-build-tools` (In admin command prompt)
```
npm config set python /path/to/executable/python2.x
npm install --global node-gyp
```
You may want to point npm to the most recent version of python 3 you have installed after this is done.  It seems that the code used to build fibers uses Python 2.x print styles.

Then you should be able to install fibers and the other things.
