### ISSUE TITLE
Plugin Page In Mobile Problem

### ISSUE THREAD

**Issue by arepson** [gridsome/gridsome.org#425]
When I visit link (example) https://gridsome.org/plugins/gridsome-source-google-sheets in mobile just show blank, I scrolled down nothing can see

**Comment by tomtev** [comment]
You're right! We will have this fixed

**Comment by Kulcanhez** [comment]
This happens also to me on iPhone 8 with the latest iOS. 🙂

**Comment by 12vanblart** [comment]
To help jumpstart debugging this: 

I'm also able to emulate this in Chrome's Mobile Debugging tools - so it's probably an issue with this specific window size and how CSS is applying.

**Comment by 12vanblart** [comment]
Looked into this more and I _think_ undoing #302 will fix this - but I'm not sure if it'll bring back issues fixed by that PR. 

It looks to be okay at all breakpoints, presumably from when the CSS changed to move the Search plugins list after the plugin docs `section`. Not sure which PRs made this change to check what exactly changed at that time.

**Comment by amykble** [comment]
Also seeing this on Samsung s8 and ipad mini
